name: github-webhooks

services:
  redis:
    image: redis/redis-stack
    container_name: webhooks-redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  redis:
